version: '3.7'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_username
      WORDPRESS_DB_PASSWORD: db_password
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_username
      - db_password

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_username
      - db_password

volumes:
  wordpress_data:
  db_data:

secrets:
   db_username:
    file: db_username.txt
   db_password:
    file: db_password.txt
